import * as esbuild from "esbuild";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

// 构建配置
const BUILD_DIR = "build";
const RELEASE_DIR = "release";

// 入口点配置
const ENTRY_POINTS = [
  { name: "agent", entry: "agent.ts" },
];

// pkg 目标平台配置
const PKG_TARGETS = [
  "node20-macos-x64",
  "node20-macos-arm64",
  "node20-linux-x64",
  "node20-win-x64",
];

// 清理目录
function cleanDir(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true });
  }
  fs.mkdirSync(dir, { recursive: true });
}

// 使用 esbuild 构建 CommonJS 包
async function buildWithEsbuild() {
  console.log("📦 使用 esbuild 构建 CommonJS 包...\n");

  cleanDir(BUILD_DIR);

  for (const { name, entry } of ENTRY_POINTS) {
    console.log(`  构建 ${name}...`);

    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      platform: "node",
      target: "node20",
      format: "cjs",
      outfile: `${BUILD_DIR}/${name}.cjs`,
      minify: false, // 保持可读性，方便调试
      sourcemap: false,
      // 排除无法打包的原生模块
      external: [],
      // 处理 __dirname 和 __filename
      define: {},
      // 允许动态 require
      banner: {
        js: `
// Generated by esbuild - CommonJS bundle
const __importMetaUrl = require('url').pathToFileURL(__filename).href;
`,
      },
    });

    const stats = fs.statSync(`${BUILD_DIR}/${name}.cjs`);
    console.log(`  ✅ ${name}.cjs (${(stats.size / 1024).toFixed(1)} KB)`);
  }

  console.log("\n✅ esbuild 构建完成\n");
}

// 使用 pkg 打包可执行文件
async function packageWithPkg() {
  console.log("🔧 使用 pkg 打包可执行文件...\n");

  cleanDir(RELEASE_DIR);

  for (const { name } of ENTRY_POINTS) {
    const inputFile = `${BUILD_DIR}/${name}.cjs`;

    for (const target of PKG_TARGETS) {
      const [, os, arch] = target.match(/node\d+-(\w+)-(\w+)/);
      const ext = os === "win" ? ".exe" : "";
      const outputName = `${name}-${os}-${arch}${ext}`;
      const outputPath = `${RELEASE_DIR}/${outputName}`;

      console.log(`  打包 ${outputName}...`);

      try {
        execSync(
          `npx pkg ${inputFile} --target ${target} --output ${outputPath}`,
          {
            stdio: "pipe",
          }
        );

        const stats = fs.statSync(outputPath);
        console.log(
          `  ✅ ${outputName} (${(stats.size / 1024 / 1024).toFixed(1)} MB)`
        );
      } catch (error) {
        console.error(`  ❌ 打包 ${outputName} 失败:`, error.message);
      }
    }
  }

  console.log("\n✅ pkg 打包完成\n");
}

// 生成 SHA256 校验和
function generateChecksums() {
  console.log("🔐 生成 SHA256 校验和...\n");

  const checksums = [];
  const files = fs.readdirSync(RELEASE_DIR);

  for (const file of files) {
    if (file === "checksums.txt") continue;

    const filePath = path.join(RELEASE_DIR, file);
    const hash = execSync(`shasum -a 256 "${filePath}"`).toString().trim();
    checksums.push(hash);
    console.log(`  ${hash.split("  ")[0].slice(0, 16)}... ${file}`);
  }

  fs.writeFileSync(`${RELEASE_DIR}/checksums.txt`, checksums.join("\n") + "\n");
  console.log(`\n✅ checksums.txt 已生成\n`);
}

// 显示构建结果
function showResults() {
  console.log("═".repeat(60));
  console.log("📋 构建结果");
  console.log("═".repeat(60));

  const files = fs.readdirSync(RELEASE_DIR);
  for (const file of files) {
    const filePath = path.join(RELEASE_DIR, file);
    const stats = fs.statSync(filePath);
    const size =
      stats.size > 1024 * 1024
        ? `${(stats.size / 1024 / 1024).toFixed(1)} MB`
        : `${(stats.size / 1024).toFixed(1)} KB`;
    console.log(`  ${file.padEnd(35)} ${size}`);
  }

  console.log("═".repeat(60));
  console.log(`\n💡 使用方法:`);
  console.log(`   macOS (Intel):  ./release/agent-macos-x64`);
  console.log(`   macOS (Apple):  ./release/agent-macos-arm64`);
  console.log(`   Linux:          ./release/agent-linux-x64`);
  console.log(`   Windows:        .\\release\\agent-win-x64.exe`);
  console.log("");
}

// 主函数
async function main() {
  const args = process.argv.slice(2);
  const skipPkg = args.includes("--skip-pkg");

  console.log("");
  console.log("╔══════════════════════════════════════════════════════════════╗");
  console.log("║              🚀 Build Release Packages                        ║");
  console.log("╚══════════════════════════════════════════════════════════════╝");
  console.log("");

  try {
    // 步骤 1: esbuild 构建
    await buildWithEsbuild();

    if (!skipPkg) {
      // 步骤 2: pkg 打包
      await packageWithPkg();

      // 步骤 3: 生成校验和
      generateChecksums();

      // 显示结果
      showResults();
    } else {
      console.log("⏭️  跳过 pkg 打包 (--skip-pkg)\n");
      console.log(`📁 CommonJS 包已生成到 ${BUILD_DIR}/ 目录`);
    }
  } catch (error) {
    console.error("\n❌ 构建失败:", error);
    process.exit(1);
  }
}

main();

